[package]
name = "cosmic-applet-clockify"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19"
wayland-client = "0.29"  # or your preferred version
wayland-protocols = { version = "0.32", features = ["staging", "client"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["applet", "wayland", "tokio"]
